server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_website
    username: root
    password: Root123$
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update # create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
